import json
import re
import time
from pathlib import Path

from backend.core import audit as audit
from backend.core import runtime_store as store

ROOT = Path(__file__).resolve().parents[1]
DATA_DIR = ROOT / "data"
SKILLS_DIR = DATA_DIR / "skills"

BUILTINS = {
    "general": {
        "description": "Default conversational and planning behavior.",
        "allowed_task_modes": ["chat", "research", "code", "write", "organize", "analyze"],
        "allowed_tools": ["rag_search", "graph_search"],
        "default_model_role": "main",
        "required_permissions": ["allow_file_read"],
        "content": "",
    },
    "folder_organizer": {
        "description": "Create a local folder organization plan and request approvals for moves.",
        "allowed_task_modes": ["organize"],
        "allowed_tools": ["fs_list", "fs_mkdir", "fs_move"],
        "default_model_role": "organizer",
        "required_permissions": ["allow_file_read", "allow_file_reorganize"],
        "content": """from collections import defaultdict
from pathlib import Path

GROUPS = {
    "documents": {".pdf", ".doc", ".docx", ".txt", ".md", ".rtf"},
    "spreadsheets": {".xls", ".xlsx", ".csv", ".tsv"},
    "images": {".png", ".jpg", ".jpeg", ".gif", ".webp", ".svg"},
    "code": {".py", ".js", ".html", ".css", ".json", ".yml", ".yaml", ".toml"},
    "archives": {".zip", ".7z", ".rar", ".tar", ".gz"},
}

def bucket(name):
    suffix = Path(name).suffix.lower()
    for group, exts in GROUPS.items():
        if suffix in exts:
            return group
    return "misc"

async def run(objective, plan, mcp, log):
    log("scanning folder")
    listing = await mcp.call_tool("fs_list", {"path": "."})
    moves = []
    grouped = defaultdict(list)
    for item in listing.get("items", []):
        if item["kind"] != "file":
            continue
        group = bucket(item["name"])
        grouped[group].append(item["name"])
        moves.append((item["name"], f"{group}/{item['name']}"))

    lines = ["Folder organization plan:", ""]
    for group, names in grouped.items():
        lines.append(f"{group}:")
        for name in names[:25]:
            lines.append(f"- {name}")

    moved = []
    for src, dst in moves:
        try:
            await mcp.call_tool("fs_mkdir", {"path": str(Path(dst).parent)})
            await mcp.call_tool("fs_move", {"source": src, "target": dst})
            moved.append(f"{src} -> {dst}")
        except PermissionError:
            lines.append("")
            lines.append("Reorganize permission is off, so this is a plan only.")
            break
        except Exception as exc:
            moved.append(f"skip {src}: {exc}")

    if moved:
        lines.append("")
        lines.append("Moved:")
        lines.extend(f"- {x}" for x in moved)
    return "\\n".join(lines)
"""
    },
    "web_research": {
        "description": "Use the brokered web-search tool after approval.",
        "allowed_task_modes": ["research"],
        "allowed_tools": ["web_search"],
        "default_model_role": "researcher",
        "required_permissions": ["allow_web_search"],
        "content": """async def run(objective, plan, mcp, log):
    log("searching web")
    search = await mcp.call_tool("web_search", {"query": objective, "max_results": 5})
    lines = [f"Research task: {objective}", "", "Plan:", plan, "", "Search hits:"]
    for item in search.get("results", []):
        lines.append(f"- {item.get('title', 'untitled')}")
    if search.get("error"):
        lines.append(f"Search error: {search['error']}")
    return "\\n".join(lines)
"""
    },
    "paper_writer": {
        "description": "Draft structured writing from local context.",
        "allowed_task_modes": ["write"],
        "allowed_tools": ["rag_search", "graph_search"],
        "default_model_role": "writer",
        "required_permissions": ["allow_file_read"],
        "content": """async def run(objective, plan, mcp, log):
    log("drafting paper outline")
    title = objective.strip().capitalize()
    return f\"\"\"# {title}

## Thesis
TBD, but make it sharp.

## Outline
1. Context
2. Main argument
3. Evidence
4. Counterpoint
5. Conclusion

## Plan Notes
{plan}
\"\"\"
"""
    },
    "excel_data_entry": {
        "description": "Plan spreadsheet-oriented data entry workflows.",
        "allowed_task_modes": ["write", "analyze"],
        "allowed_tools": ["rag_search"],
        "default_model_role": "executor",
        "required_permissions": ["allow_file_read"],
        "content": """import csv
import io

async def run(objective, plan, mcp, log):
    log("making csv stub")
    rows = [
        ["task", "status", "notes"],
        [objective, "new", "generated by local hub"],
        ["follow up", "todo", "fill with real spreadsheet workflow"],
    ]
    out = io.StringIO()
    writer = csv.writer(out)
    writer.writerows(rows)
    await mcp.call_tool("fs_write", {"path": "data/excel_task_stub.csv", "content": out.getvalue()})
    return "Wrote data/excel_task_stub.csv\\n\\n" + out.getvalue()
"""
    },
}


def _slug(name):
    return re.sub(r"[^a-zA-Z0-9_.-]+", "-", str(name or "")).strip("-").lower()[:64] or "skill"


def _skill_path(name):
    return SKILLS_DIR / _slug(name) / "SKILL.md"


def _markdown(name, metadata):
    lines = [
        f"# {name}",
        "",
        metadata.get("description", "Reusable Rasputin skill."),
        "",
        "```json",
        json.dumps(metadata, indent=2, ensure_ascii=True),
        "```",
        "",
        "## Workflow",
        "",
        "- Read the task and active workspace.",
        "- Use only allowed tools.",
        "- Ask for approval before risky actions.",
        "- Return a concise result with outputs when useful.",
    ]
    return "\n".join(lines) + "\n"


def init_skills():
    store.init_db()
    stamp = store.now()
    with store._lock, store.connect() as conn:
        for name, metadata in BUILTINS.items():
            content = metadata.get("content", "")
            # We no longer use physical files for built-in action skills
            conn.execute(
                """
                INSERT INTO skills(name,description,metadata,enabled,builtin,path,content,created_at,updated_at)
                VALUES(?,?,?,?,?,?,?,?,?)
                ON CONFLICT(name) DO UPDATE SET description=excluded.description, metadata=excluded.metadata, builtin=1, content=excluded.content, updated_at=excluded.updated_at
                """,
                (name, metadata.get("description", ""), json.dumps(metadata), 1, 1, "", content, stamp, stamp),
            )
        conn.commit()


def _public(row, include_content=False):
    data = dict(row)
    data["metadata"] = store._loads(data.get("metadata"), {})
    data["enabled"] = bool(data.get("enabled"))
    data["builtin"] = bool(data.get("builtin"))
    if not include_content:
        data.pop("content", None)
    return data


def list_skills(include_disabled=True):
    init_skills()
    where = "" if include_disabled else "WHERE enabled=1"
    with store._lock, store.connect() as conn:
        rows = conn.execute(f"SELECT * FROM skills {where} ORDER BY builtin DESC, name").fetchall()
    return {"skills": [_public(row) for row in rows]}


def enabled_names():
    return [item["name"] for item in list_skills(False)["skills"]]


def get_skill(name):
    init_skills()
    with store._lock, store.connect() as conn:
        row = conn.execute("SELECT * FROM skills WHERE name=?", (_slug(name),)).fetchone()
    if not row:
        raise ValueError("skill missing")
    return _public(row, include_content=True)


def save_skill(name, description, content=None, metadata=None, builtin=False):
    init_skills()
    name = _slug(name)
    metadata = metadata or {}
    metadata.setdefault("description", description or "Reusable Rasputin skill.")
    stamp = store.now()
    content_val = content or _markdown(name, metadata)
    with store._lock, store.connect() as conn:
        conn.execute(
            """
            INSERT INTO skills(name,description,metadata,enabled,builtin,path,content,created_at,updated_at)
            VALUES(?,?,?,?,?,?,?,?,?)
            ON CONFLICT(name) DO UPDATE SET description=excluded.description, metadata=excluded.metadata, content=excluded.content, updated_at=excluded.updated_at
            """,
            (name, description or metadata.get("description", ""), json.dumps(metadata), 1, int(bool(builtin)), "", content_val, stamp, stamp),
        )
        conn.commit()
    audit.log("skill_saved", {"name": name, "builtin": builtin})
    return get_skill(name)


def import_skill(name, content, metadata=None):
    if not str(content or "").strip():
        raise ValueError("skill content is required")
    return save_skill(name, (metadata or {}).get("description", "Imported Rasputin skill."), content, metadata or {})


def set_enabled(name, enabled):
    init_skills()
    with store._lock, store.connect() as conn:
        row = conn.execute("SELECT name FROM skills WHERE name=?", (_slug(name),)).fetchone()
        if not row:
            raise ValueError("skill missing")
        conn.execute("UPDATE skills SET enabled=?, updated_at=? WHERE name=?", (1 if enabled else 0, store.now(), _slug(name)))
        conn.commit()
    audit.log("skill_enabled" if enabled else "skill_disabled", {"name": _slug(name)})
    return get_skill(name)


def create_from_session(session_id, name=None, save=False):
    store.init_db()
    with store._lock, store.connect() as conn:
        session = conn.execute("SELECT * FROM sessions WHERE id=?", (session_id,)).fetchone()
        if not session:
            raise ValueError("session missing")
        messages = conn.execute(
            "SELECT role, content FROM messages WHERE session_id=? ORDER BY created_at ASC LIMIT 20",
            (session_id,),
        ).fetchall()
    title = name or session["title"] or "Session Skill"
    skill_name = _slug(title)
    metadata = {
        "name": skill_name,
        "description": f"Reusable workflow distilled from session {session_id}.",
        "allowed_task_modes": [session["mode"]],
        "allowed_tools": ["rag_search", "graph_search"],
        "default_model_role": session["model"] or "main",
        "required_permissions": ["allow_file_read"],
        "workspace_constraints": session["workspace"],
    }
    content = _markdown(skill_name, metadata) + "\n## Session Notes\n\n"
    for row in messages[-8:]:
        content += f"- **{row['role']}**: {row['content'][:600]}\n"
    preview = {"name": skill_name, "metadata": metadata, "content": content, "preview": not save}
    if save:
        return save_skill(skill_name, metadata["description"], content, metadata)
    audit.log("skill_preview_created", {"session_id": session_id, "name": skill_name})
    return preview


init_skills()
