import hashlib
import json
import os
import re
import tempfile
from collections import Counter, defaultdict
from datetime import datetime, timezone
from pathlib import Path
from threading import Lock

from backend.core import workspace
from backend.rag import graph as graphify
from backend.rag import vector as rag


EXPORT_DIR_NAME = "Rasputin Graph"
NODES_DIR_NAME = "Nodes"
MANIFEST_NAME = ".rasputin-export.json"
EXPORT_VERSION = 1
_lock = Lock()


def _slug(value, fallback="node", limit=56):
    text = re.sub(r"[^a-zA-Z0-9_-]+", "-", str(value or "")).strip("-").lower()
    return (text[:limit] or fallback).strip("-") or fallback


def _node_filename(node):
    node_id = str(node.get("id") or node.get("name") or "node")
    digest = hashlib.sha256(node_id.encode("utf-8")).hexdigest()[:10]
    kind = _slug(node.get("kind"), "concept", 24)
    name = _slug(node.get("name"), "node", 48)
    return f"{kind}--{name}--{digest}.md"


def _yaml_string(value):
    # JSON strings are valid YAML scalar syntax and safely quote punctuation.
    return json.dumps(str(value or ""), ensure_ascii=False)


def _wiki_alias(value):
    return " ".join(str(value or "Unnamed node").split()).replace("|", "\\|")


def _wiki_link(node, note_targets):
    target = note_targets.get(str(node.get("id") or ""))
    if not target:
        return _wiki_alias(node.get("name"))
    return f"[[{target}|{_wiki_alias(node.get('name'))}]]"


def _location(evidence):
    citation = (evidence or {}).get("citation") or {}
    path = citation.get("path") or (evidence or {}).get("path") or "local source"
    if citation.get("page_start"):
        return f"{path}, page {citation['page_start']}"
    if citation.get("sheet_name"):
        rows = f"{citation.get('row_start') or '?'}-{citation.get('row_end') or '?'}"
        return f"{path}, {citation['sheet_name']} rows {rows}"
    if citation.get("line_start"):
        end = citation.get("line_end") or citation.get("line_start")
        return f"{path}, lines {citation['line_start']}-{end}"
    return str(path)


def _relation_line(edge, other, note_targets, direction):
    relation = str(edge.get("relation") or edge.get("type") or "related_to")
    arrow = "→" if direction == "out" else "←"
    weight = edge.get("weight")
    confidence = edge.get("confidence")
    details = []
    if weight is not None:
        details.append(f"weight {weight}")
    if confidence is not None:
        details.append(f"confidence {confidence}")
    suffix = f" ({'; '.join(details)})" if details else ""
    return f"- `{relation}` {arrow} {_wiki_link(other, note_targets)}{suffix}"


def _node_note(node, outgoing, incoming, nodes_by_id, note_targets):
    node_id = str(node.get("id") or "")
    name = " ".join(str(node.get("name") or "Unnamed node").split())
    kind = str(node.get("kind") or "concept")
    relation_tags = sorted({
        _slug(edge.get("relation") or edge.get("type"), "related")
        for edge in outgoing + incoming
    })
    lines = [
        "---",
        "rasputin_generated: true",
        f"rasputin_id: {_yaml_string(node_id)}",
        f"rasputin_kind: {_yaml_string(kind)}",
        f"weight: {int(node.get('weight') or 0)}",
        "aliases:",
        f"  - {_yaml_string(name)}",
        "tags:",
        "  - rasputin-graph",
        f"  - rasputin-graph/{_slug(kind, 'concept')}",
    ]
    lines.extend(f"  - rasputin-relation/{tag}" for tag in relation_tags)
    lines.extend([
        "---",
        "",
        f"# {name}",
        "",
        "> Generated by Rasputin. Re-exporting refreshes this managed note.",
        "",
        f"- **Kind:** {kind}",
        f"- **Weight:** {int(node.get('weight') or 0)}",
    ])

    sources = [str(source) for source in node.get("sources", []) if source]
    if sources:
        lines.extend(["", "## Sources", ""])
        lines.extend(f"- `{source}`" for source in sources)

    if outgoing:
        lines.extend(["", "## Outgoing relationships", ""])
        for edge in outgoing:
            other = nodes_by_id.get(str(edge.get("target_id") or ""), {
                "id": edge.get("target_id"), "name": edge.get("target")
            })
            lines.append(_relation_line(edge, other, note_targets, "out"))

    if incoming:
        lines.extend(["", "## Incoming relationships", ""])
        for edge in incoming:
            other = nodes_by_id.get(str(edge.get("source_id") or ""), {
                "id": edge.get("source_id"), "name": edge.get("source")
            })
            lines.append(_relation_line(edge, other, note_targets, "in"))

    evidence = node.get("evidence", [])[:8]
    if evidence:
        lines.extend(["", "## Evidence", ""])
        for item in evidence:
            snippet = " ".join(str(item.get("snippet") or "").split())[:280]
            detail = f" — {snippet}" if snippet else ""
            lines.append(f"- `{_location(item)}`{detail}")

    return "\n".join(lines).rstrip() + "\n"


def _index_note(graph, note_targets, workspace_name, source_path, generated_at):
    nodes = graph.get("nodes", [])
    edges = graph.get("edges", [])
    kinds = Counter(str(node.get("kind") or "concept") for node in nodes)
    relations = Counter(str(edge.get("relation") or edge.get("type") or "related_to") for edge in edges)
    lines = [
        "---",
        "rasputin_generated: true",
        "tags:",
        "  - rasputin-graph",
        "  - rasputin-graph/index",
        "---",
        "",
        "# Rasputin Knowledge Graph",
        "",
        "> Generated by Rasputin from the selected workspace. Re-export to refresh it.",
        "",
        f"- **Workspace:** {workspace_name}",
        f"- **Source:** `{source_path}`",
        f"- **Generated:** {generated_at}",
        f"- **Nodes:** {len(nodes)}",
        f"- **Relationships:** {len(edges)}",
        "",
        "## Node kinds",
        "",
    ]
    lines.extend(f"- **{kind}:** {count}" for kind, count in sorted(kinds.items()))
    lines.extend(["", "## Relationship types", ""])
    lines.extend(f"- **{relation}:** {count}" for relation, count in sorted(relations.items()))
    lines.extend(["", "## Top nodes", ""])
    for node in nodes[:25]:
        lines.append(f"- {_wiki_link(node, note_targets)} — {node.get('kind') or 'concept'}, weight {node.get('weight') or 0}")
    lines.extend([
        "",
        f"All generated notes live in `{EXPORT_DIR_NAME}/{NODES_DIR_NAME}`. "
        "The links between those notes power Obsidian Graph View.",
    ])
    return "\n".join(lines).rstrip() + "\n"


def _atomic_write(path, content):
    path.parent.mkdir(parents=True, exist_ok=True)
    handle = tempfile.NamedTemporaryFile(
        mode="w", encoding="utf-8", newline="\n", delete=False,
        dir=str(path.parent), prefix=f".{path.name}.", suffix=".tmp",
    )
    temp_path = Path(handle.name)
    try:
        with handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temp_path, path)
    finally:
        temp_path.unlink(missing_ok=True)


def _is_generated_note(path):
    try:
        return "rasputin_generated: true" in path.read_text(encoding="utf-8")[:512]
    except (OSError, UnicodeError):
        return False


def export_workspace(path=None):
    target, item, _root = rag._scope(path or ".")
    if not target.exists() or not target.is_dir():
        raise ValueError("Obsidian export requires a workspace folder")
    workspace.require_path_permission(target, "write")

    # Refresh first so every explicit export represents the current files,
    # rather than whichever workspace happened to build the global graph last.
    rag_result = rag.ingest(str(target), item.get("name") or target.name)
    graph_result = graphify.build(str(target))
    graph = graphify.raw_graph()

    export_root = target / EXPORT_DIR_NAME
    nodes_dir = export_root / NODES_DIR_NAME
    if export_root.exists() and (export_root.is_symlink() or not export_root.is_dir()):
        raise ValueError(f"{EXPORT_DIR_NAME} must be a regular folder")
    if nodes_dir.exists() and (nodes_dir.is_symlink() or not nodes_dir.is_dir()):
        raise ValueError(f"{EXPORT_DIR_NAME}/{NODES_DIR_NAME} must be a regular folder")

    nodes = graph.get("nodes", [])
    edges = graph.get("edges", [])
    nodes_by_id = {str(node.get("id") or ""): node for node in nodes}
    filenames = {str(node.get("id") or ""): _node_filename(node) for node in nodes}
    note_targets = {
        node_id: f"{EXPORT_DIR_NAME}/{NODES_DIR_NAME}/{filename[:-3]}"
        for node_id, filename in filenames.items()
    }
    outgoing = defaultdict(list)
    incoming = defaultdict(list)
    for edge in edges:
        outgoing[str(edge.get("source_id") or "")].append(edge)
        incoming[str(edge.get("target_id") or "")].append(edge)

    generated_at = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
    generated_files = {"Index.md"}
    generated_files.update(f"{NODES_DIR_NAME}/{filename}" for filename in filenames.values())

    with _lock:
        nodes_dir.mkdir(parents=True, exist_ok=True)
        for node_id, node in nodes_by_id.items():
            _atomic_write(
                nodes_dir / filenames[node_id],
                _node_note(node, outgoing[node_id], incoming[node_id], nodes_by_id, note_targets),
            )
        _atomic_write(
            export_root / "Index.md",
            _index_note(graph, note_targets, item.get("name") or target.name, str(target), generated_at),
        )

        removed = 0
        for old_note in nodes_dir.glob("*.md"):
            relative = f"{NODES_DIR_NAME}/{old_note.name}"
            if relative not in generated_files and _is_generated_note(old_note):
                old_note.unlink()
                removed += 1

        manifest = {
            "version": EXPORT_VERSION,
            "generated_at": generated_at,
            "workspace_id": item.get("id"),
            "source_path": str(target),
            "nodes": len(nodes),
            "edges": len(edges),
            "generated_files": sorted(generated_files),
        }
        _atomic_write(export_root / MANIFEST_NAME, json.dumps(manifest, indent=2, ensure_ascii=False) + "\n")

    return {
        "path": str(export_root),
        "relative_path": f"{EXPORT_DIR_NAME}/Index.md",
        "workspace_id": item.get("id"),
        "nodes_exported": len(nodes),
        "edges_exported": len(edges),
        "files_written": len(generated_files),
        "stale_files_removed": removed,
        "generated_at": generated_at,
        "rag_result": rag_result,
        "graph_result": graph_result,
    }
