import csv
import io


async def run(objective, plan, mcp, log):
    log("making csv stub")
    rows = [
        ["task", "status", "notes"],
        [objective, "new", "generated by local hub"],
        ["follow up", "todo", "fill with real spreadsheet workflow"],
    ]
    out = io.StringIO()
    writer = csv.writer(out)
    writer.writerows(rows)
    await mcp.call_tool("fs_write", {"path": "data/excel_task_stub.csv", "content": out.getvalue()})
    return "Wrote data/excel_task_stub.csv\n\n" + out.getvalue()
